active:
  zdp: dev
server:
  port: 8080

spring:
  datasource:
    data1:
      jdbc-url: jdbc:postgresql://10.100.20.211:5432/i20_gateway
      url: jdbc:postgresql://10.100.20.211:5432/i20_gateway
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
      driverClassName: org.postgresql.Driver
      type: com.alibaba.druid.pool.DruidDataSource   # 使用druid数据库连接池
      filters: stat,wall,log4j   #druid 监控配置
    data2:
      jdbc-url: jdbc:postgresql://10.100.20.211:5432/spk_manager2
      url: jdbc:postgresql://10.100.20.211:5432/spk_manager2
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
      driverClassName: org.postgresql.Driver
      type: com.alibaba.druid.pool.DruidDataSource   # 使用druid数据库连接池
      filters: stat,wall,log4j   #druid 监控配
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter: stat,wall,log4j   #druid 监控配置
      log-slow-sql: true

#日志打印的输出路径
log_refer :      D:\xm\hd_springboot\logs