spring:
  profiles:
    active: @profiles.active@

server:
  port: 8080


mybatis:
#  mapper-locations: classpath:*/mapping/**.xml
  type-aliases-package: com.hd.beast.entity


#在控制台打印sql日志
logging:
  level:
    com.hd.beast.mapper.mapper1 : debug
